[Room."Dark Room"]
description = "You are in a [bold]dark room[/]."
label = "Dark Room"

[Room."Valley"]
description = "You are in a [bold]beautiful valley[/]."
label = "Valley"

[Room."Magic Forest"]
description = "You are in a [bold]enchanted forest[/] where magic grows wildly."
label = "Magic Forest"

[Item."rusty mallet"]
aliases = ["mallet"]
